# 执行委员' })
User.create(name: "ch00001", password: "pa4sswor1d", is_admin: false, role: ["执委"], company_name: "执委：江廷科", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00002", password: "pas5swor1d", is_admin: false, role: ["执委"], company_name: "执委：张显峰", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00003", password: "pa6sswor1d", is_admin: false, role: ["执委"], company_name: "执委：陆标", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00004", password: "pas7swor1d", is_admin: false, role: ["执委"], company_name: "执委：王长平", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00005", password: "pas3swor1d", is_admin: false, role: ["执委"], company_name: "执委：傅  平", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00006", password: "pa6sswor1d", is_admin: false, role: ["执委"], company_name: "执委：郑世茂", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00007", password: "pass7wo1rd", is_admin: false, role: ["执委"], company_name: "执委：赵晓红", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00008", password: "pa3ssw1ord", is_admin: false, role: ["执委"], company_name: "执委：王家辉", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00009", password: "pas6s2word", is_admin: false, role: ["执委"], company_name: "执委：魏  铭", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00010", password: "pa7sswor3d", is_admin: false, role: ["执委"], company_name: "执委：姜总祥", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00011", password: "pa5sswo3rd", is_admin: false, role: ["执委"], company_name: "执委：黄春元", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00012", password: "pas7sw3ord", is_admin: false, role: ["执委"], company_name: "执委：高维英", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00013", password: "2pass3word", is_admin: false, role: ["执委"], company_name: "执委：薛海涛", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00014", password: "p3asswor3d", is_admin: false, role: ["执委"], company_name: "执委：王德江", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00015", password: "pa4sswo3rd", is_admin: false, role: ["执委"], company_name: "执委：陈文景", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00016", password: "pas5sw3ord", is_admin: false, role: ["执委"], company_name: "执委：李国超", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00017", password: "pass6wo3rd", is_admin: false, role: ["执委"], company_name: "执委：朱吉满", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00018", password: "passw17ord", is_admin: false, role: ["执委"], company_name: "执委：郭锡哲", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00019", password: "passwo24rd", is_admin: false, role: ["执委"], company_name: "执委：杨广利", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00020", password: "pass3wor3d", is_admin: false, role: ["执委"], company_name: "执委：刘来祥", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00021", password: "4passwo3rd", is_admin: false, role: ["执委"], company_name: "执委：马海龙", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00022", password: "p5asswo2rd", is_admin: false, role: ["执委"], company_name: "执委：李  霏", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00023", password: "p6assw3ord", is_admin: false, role: ["执委"], company_name: "执委：姜  涛", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00024", password: "p7asswor3d", is_admin: false, role: ["执委"], company_name: "执委：张世卓", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00025", password: "pa8sswor2d", is_admin: false, role: ["执委"], company_name: "执委：王  舰", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00026", password: "pass7wo1rd", is_admin: false, role: ["执委"], company_name: "执委：张宇晖", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00027", password: "passw4o2rd", is_admin: false, role: ["执委"], company_name: "执委：王笑卓", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00028", password: "passw2o2rd", is_admin: false, role: ["执委"], company_name: "执委：韩兴东", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00029", password: "pass4wo3rd", is_admin: false, role: ["执委"], company_name: "执委：李志刚", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00030", password: "passw53ord", is_admin: false, role: ["执委"], company_name: "执委：吴金铨", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00031", password: "passw46ord", is_admin: false, role: ["执委"], company_name: "执委：冯嘉伦", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00032", password: "pass3wo3rd", is_admin: false, role: ["执委"], company_name: "执委：刘  洋", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00033", password: "pas2swo5rd", is_admin: false, role: ["执委"], company_name: "执委：杨亚宁", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00034", password: "pwd79a80", is_admin: false, role: ["执委"], company_name: "执委：何文辉", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00035", password: "pwd80c45", is_admin: false, role: ["执委"], company_name: "执委：吴庆和", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00036", password: "pwdj1343", is_admin: false, role: ["执委"], company_name: "执委：陈为坤", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00037", password: "pwd31e18", is_admin: false, role: ["执委"], company_name: "执委：韩鲁波", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00038", password: "pwd33r87", is_admin: false, role: ["执委"], company_name: "执委：崔立滨", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00039", password: "pwd9t320", is_admin: false, role: ["执委"], company_name: "执委：袁  勃", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00040", password: "pwd65y22", is_admin: false, role: ["执委"], company_name: "执委：满伟男", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00041", password: "pwd6u683", is_admin: false, role: ["执委"], company_name: "执委：梅章记", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00042", password: "pwd53m91", is_admin: false, role: ["执委"], company_name: "执委：关  一", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00043", password: "pwd83j33", is_admin: false, role: ["执委"], company_name: "执委：秦剑飞", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00044", password: "pwd12g20", is_admin: false, role: ["执委"], company_name: "执委：杨昌仁", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00045", password: "pwd8y115", is_admin: false, role: ["执委"], company_name: "执委：郑晓苹", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00046", password: "pwd6u677", is_admin: false, role: ["执委"], company_name: "执委：杨秀芳", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00047", password: "pwd16u64", is_admin: false, role: ["执委"], company_name: "执委：张　勉", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00048", password: "pwd6i209", is_admin: false, role: ["执委"], company_name: "执委：尹  源", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00049", password: "pwd87o00", is_admin: false, role: ["执委"], company_name: "执委：张德毅", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00050", password: "pwd72p82", is_admin: false, role: ["执委"], company_name: "执委：贾秀芳", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00051", password: "pwd74i50", is_admin: false, role: ["执委"], company_name: "执委：张忠凯", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00052", password: "pwd31y21", is_admin: false, role: ["执委"], company_name: "执委：纪延超", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00053", password: "pwd58h36", is_admin: false, role: ["执委"], company_name: "执委：焦裕昌", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00054", password: "pwd80u97", is_admin: false, role: ["执委"], company_name: "执委：林建芳", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00055", password: "pwd59r14", is_admin: false, role: ["执委"], company_name: "执委：刘家滨", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00056", password: "pwd1g714", is_admin: false, role: ["执委"], company_name: "执委：杨志峰", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00057", password: "pwd1n360", is_admin: false, role: ["执委"], company_name: "执委：田立坤", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00058", password: "pwd26m18", is_admin: false, role: ["执委"], company_name: "执委：于春滨", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00059", password: "pwd25n84", is_admin: false, role: ["执委"], company_name: "执委：徐卫国", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00060", password: "pwd68k17", is_admin: false, role: ["执委"], company_name: "执委：孙永恒", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00061", password: "pwd48l17", is_admin: false, role: ["执委"], company_name: "执委：张雪涛", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00062", password: "pwd37q70", is_admin: false, role: ["执委"], company_name: "执委：刘国力", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00063", password: "pwd956d6", is_admin: false, role: ["执委"], company_name: "执委：张晓宇", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00064", password: "pwd75d48", is_admin: false, role: ["执委"], company_name: "执委：吴都奎", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00065", password: "pwd93v91", is_admin: false, role: ["执委"], company_name: "执委：于洪生", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00066", password: "pwd84b36", is_admin: false, role: ["执委"], company_name: "执委：李玉慧", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00067", password: "pwd43n05", is_admin: false, role: ["执委"], company_name: "执委：殷学中", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00068", password: "pwd90m87", is_admin: false, role: ["执委"], company_name: "执委：肖新光", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00069", password: "pwd6r735", is_admin: false, role: ["执委"], company_name: "执委：吕  晶", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00070", password: "pwd5e262", is_admin: false, role: ["执委"], company_name: "执委：潘  洋", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00071", password: "pwd79g07", is_admin: false, role: ["执委"], company_name: "执委：陈良勇", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00072", password: "pwd2h375", is_admin: false, role: ["执委"], company_name: "执委：高晓明", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00073", password: "pwd58g96", is_admin: false, role: ["执委"], company_name: "执委：张君国", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00074", password: "pwd20m88", is_admin: false, role: ["执委"], company_name: "执委：李荣金", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00075", password: "pwd24b98", is_admin: false, role: ["执委"], company_name: "执委：任中国", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00076", password: "pwd84b73", is_admin: false, role: ["执委"], company_name: "执委：颜政治", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00077", password: "pd5bv562", is_admin: false, role: ["执委"], company_name: "执委：赵洪波", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00078", password: "pwd23b38", is_admin: false, role: ["执委"], company_name: "执委：张翔得", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00079", password: "pwd10n95", is_admin: false, role: ["执委"], company_name: "执委：千玉锦", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00080", password: "pwd56v95", is_admin: false, role: ["执委"], company_name: "执委：宋建军", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00081", password: "pwd92v95", is_admin: false, role: ["执委"], company_name: "执委：张双生", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00082", password: "pwd88f77", is_admin: false, role: ["执委"], company_name: "执委：吴嘉欣", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00083", password: "pwd10b90", is_admin: false, role: ["执委"], company_name: "执委：刘海洋", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00084", password: "pwd580n0", is_admin: false, role: ["执委"], company_name: "执委：徐  伟", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00085", password: "pwd52n01", is_admin: false, role: ["执委"], company_name: "执委：王彦怀", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00086", password: "pwd91f76", is_admin: false, role: ["执委"], company_name: "执委：聂艳丽", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "ch00087", password: "pwd73t30", is_admin: false, role: ["执委"], company_name: "执委：刘艳芳", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00088", password: "pwd31y99", is_admin: false, role: ["执委"], company_name: "执委：李秋山", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00089", password: "pwd9u986", is_admin: false, role: ["执委"], company_name: "执委：冷友斌", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00090", password: "pwd66i71", is_admin: false, role: ["执委"], company_name: "执委：隋熙凤", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00091", password: "pwd68h58", is_admin: false, role: ["执委"], company_name: "执委：郭东泽", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00092", password: "pwd12h36", is_admin: false, role: ["执委"], company_name: "执委：堵留柱", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00093", password: "pwd98541", is_admin: false, role: ["执委"], company_name: "执委：潘志刚", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00094", password: "pwd97t53", is_admin: false, role: ["执委"], company_name: "执委：张亚威", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00095", password: "pwd228g1", is_admin: false, role: ["执委"], company_name: "执委：丛欧阳", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00096", password: "pwd905m2", is_admin: false, role: ["执委"], company_name: "执委：徐鹏飞", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00097", password: "pwd57k82", is_admin: false, role: ["执委"], company_name: "执委：张忠荣", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00098", password: "pwd74k56", is_admin: false, role: ["执委"], company_name: "执委：付厚文", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00099", password: "pwd90f55", is_admin: false, role: ["执委"], company_name: "执委：王建平", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00100", password: "pwd57h00", is_admin: false, role: ["执委"], company_name: "执委：钟志峰", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00101", password: "pwd53j29", is_admin: false, role: ["执委"], company_name: "执委：崔弘梅", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00102", password: "pwd48k23", is_admin: false, role: ["执委"], company_name: "执委：多继光", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00103", password: "pwd59h12", is_admin: false, role: ["执委"], company_name: "执委：赵  闯", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00104", password: "pwd25t56", is_admin: false, role: ["执委"], company_name: "执委：雷  宇", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00105", password: "pwd78u52", is_admin: false, role: ["执委"], company_name: "执委：杨寿和", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00106", password: "pwd80i47", is_admin: false, role: ["执委"], company_name: "执委：刘雅梅", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00107", password: "pwd83o28", is_admin: false, role: ["执委"], company_name: "执委：于颖娜", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00108", password: "pwd21p18", is_admin: false, role: ["执委"], company_name: "执委：王连芳", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "ch00109", password: "pwd79t41", is_admin: false, role: ["执委"], company_name: "执委：李振国", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "牡丹江" })
User.create(name: "ch00110", password: "pwd22o64", is_admin: false, role: ["执委"], company_name: "执委：倪志财", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "牡丹江" })
User.create(name: "ch00111", password: "pwd2r606", is_admin: false, role: ["执委"], company_name: "执委：王玉良", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "牡丹江" })
User.create(name: "ch00112", password: "pwd65h20", is_admin: false, role: ["执委"], company_name: "执委：邹晨星", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "牡丹江" })
User.create(name: "ch00113", password: "pwd22n35", is_admin: false, role: ["执委"], company_name: "执委：李广峰", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "牡丹江" })
User.create(name: "ch00114", password: "wd151rd6", is_admin: false, role: ["执委"], company_name: "执委：赵崇峰", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "牡丹江" })
User.create(name: "ch00115", password: "pwd88t82", is_admin: false, role: ["执委"], company_name: "执委：刘静霞", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "牡丹江" })
User.create(name: "ch00116", password: "pwd23y25", is_admin: false, role: ["执委"], company_name: "执委：齐振华", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "牡丹江" })
User.create(name: "ch00117", password: "pwd18u16", is_admin: false, role: ["执委"], company_name: "执委：张济民", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "牡丹江" })
User.create(name: "ch00118", password: "pwd85277", is_admin: false, role: ["执委"], company_name: "执委：盖少江", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "牡丹江" })
User.create(name: "ch00119", password: "pwd4q041", is_admin: false, role: ["执委"], company_name: "执委：郑俊怀", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "牡丹江" })
User.create(name: "ch00120", password: "pwd88e63", is_admin: false, role: ["执委"], company_name: "执委：毕书江", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "牡丹江" })
User.create(name: "ch00121", password: "pwd329s5", is_admin: false, role: ["执委"], company_name: "执委：郭士明", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "牡丹江" })
User.create(name: "ch00122", password: "pw829bc8", is_admin: false, role: ["执委"], company_name: "执委：陈湘舟", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "牡丹江" })
User.create(name: "ch00123", password: "pwd225b0", is_admin: false, role: ["执委"], company_name: "执委：宋雪花", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "牡丹江" })
User.create(name: "ch00124", password: "pwd339r5", is_admin: false, role: ["执委"], company_name: "执委：林文兴", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "牡丹江" })
User.create(name: "ch00125", password: "pwd526g8", is_admin: false, role: ["执委"], company_name: "执委：张敬伟", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "佳木斯" })
User.create(name: "ch00126", password: "pwd315h9", is_admin: false, role: ["执委"], company_name: "执委：姜春林", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "佳木斯" })
User.create(name: "ch00127", password: "pwd470t6", is_admin: false, role: ["执委"], company_name: "执委：周春玲", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "佳木斯" })
User.create(name: "ch00128", password: "pwd87y36", is_admin: false, role: ["执委"], company_name: "执委：王玉桐", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "佳木斯" })
User.create(name: "ch00129", password: "pwd295u2", is_admin: false, role: ["执委"], company_name: "执委：贾振江", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "佳木斯" })
User.create(name: "ch00130", password: "pwd44y27", is_admin: false, role: ["执委"], company_name: "执委：许连发", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "佳木斯" })
User.create(name: "ch00131", password: "pwd70i85", is_admin: false, role: ["执委"], company_name: "执委：郭  伟", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "佳木斯" })
User.create(name: "ch00132", password: "pwd63o50", is_admin: false, role: ["执委"], company_name: "执委：迟林明", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "佳木斯" })
User.create(name: "ch00133", password: "pwd17o57", is_admin: false, role: ["执委"], company_name: "执委：杨吉慧", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "佳木斯" })
User.create(name: "ch00134", password: "pwd13m90", is_admin: false, role: ["执委"], company_name: "执委：葛安禄", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "佳木斯" })
User.create(name: "ch00135", password: "pwd22u98", is_admin: false, role: ["执委"], company_name: "执委：张学军", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "佳木斯" })
User.create(name: "ch00136", password: "pwd27734", is_admin: false, role: ["执委"], company_name: "执委：史盛茂", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "佳木斯" })
User.create(name: "ch00137", password: "pwd57l29", is_admin: false, role: ["执委"], company_name: "执委：韩  强", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "佳木斯" })
User.create(name: "ch00138", password: "pwd32r63", is_admin: false, role: ["执委"], company_name: "执委：马良骥", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "佳木斯" })
User.create(name: "ch00139", password: "pwd55g15", is_admin: false, role: ["执委"], company_name: "执委：李  佳", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "佳木斯" })
User.create(name: "ch00140", password: "pwd32h03", is_admin: false, role: ["执委"], company_name: "执委：管军", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "佳木斯" })
User.create(name: "ch00141", password: "pwd69r45", is_admin: false, role: ["执委"], company_name: "执委：栾  红", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00142", password: "pwd81t29", is_admin: false, role: ["执委"], company_name: "执委：王  揕", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00143", password: "pwd20y02", is_admin: false, role: ["执委"], company_name: "执委：高金鹏", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00144", password: "pwd4u349", is_admin: false, role: ["执委"], company_name: "执委：阮安源", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00145", password: "pwd99u63", is_admin: false, role: ["执委"], company_name: "执委：吕乐扬", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00146", password: "pwd8i825", is_admin: false, role: ["执委"], company_name: "执委：常广义", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00147", password: "pwd61y12", is_admin: false, role: ["执委"], company_name: "执委：王占领", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00148", password: "pwd267e9", is_admin: false, role: ["执委"], company_name: "执委：滕  飞", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00149", password: "pwd77t16", is_admin: false, role: ["执委"], company_name: "执委：李晓波", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00150", password: "pwd88y37", is_admin: false, role: ["执委"], company_name: "执委：陈光吾", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00151", password: "pwd465q7", is_admin: false, role: ["执委"], company_name: "执委：张雪松", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00152", password: "pwd2749r", is_admin: false, role: ["执委"], company_name: "执委：吕永刚", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00153", password: "pwd853t1", is_admin: false, role: ["执委"], company_name: "执委：蒋少炳", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00154", password: "pwd147y0", is_admin: false, role: ["执委"], company_name: "执委：陈炳奇", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00155", password: "pwd878h4", is_admin: false, role: ["执委"], company_name: "执委：孟  浩", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00156", password: "pwd586g1", is_admin: false, role: ["执委"], company_name: "执委：杨天一", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00157", password: "pwd151m8", is_admin: false, role: ["执委"], company_name: "执委：刘  君", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00158", password: "pwd68r01", is_admin: false, role: ["执委"], company_name: "执委：薛剑栋", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00159", password: "pwd12g87", is_admin: false, role: ["执委"], company_name: "执委：田  青", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00160", password: "pwd46s72", is_admin: false, role: ["执委"], company_name: "执委：袁晓丽", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00161", password: "pwdg1276", is_admin: false, role: ["执委"], company_name: "执委：马春杰", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00162", password: "pwd4d493", is_admin: false, role: ["执委"], company_name: "执委：崔保庆", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "ch00163", password: "pwd40g14", is_admin: false, role: ["执委"], company_name: "执委：王勇进", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鸡西" })
User.create(name: "ch00164", password: "pwd91b53", is_admin: false, role: ["执委"], company_name: "执委：陈永生", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鸡西" })
User.create(name: "ch00165", password: "pwd208n2", is_admin: false, role: ["执委"], company_name: "执委：方小东", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鸡西" })
User.create(name: "ch00166", password: "pwd947f6", is_admin: false, role: ["执委"], company_name: "执委：徐昌伟", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鸡西" })
User.create(name: "ch00167", password: "pwd58r23", is_admin: false, role: ["执委"], company_name: "执委：徐松鹤", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鸡西" })
User.create(name: "ch00168", password: "pwd2t411", is_admin: false, role: ["执委"], company_name: "执委：王明坤", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鸡西" })
User.create(name: "ch00169", password: "pwd31t01", is_admin: false, role: ["执委"], company_name: "执委：赵  行", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鸡西" })
User.create(name: "ch00170", password: "pwd79w35", is_admin: false, role: ["执委"], company_name: "执委：闫  华", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鸡西" })
User.create(name: "ch00171", password: "pwd43r91", is_admin: false, role: ["执委"], company_name: "执委：王振发", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鸡西" })
User.create(name: "ch00172", password: "pwd75t83", is_admin: false, role: ["执委"], company_name: "执委：韩玉凤", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鸡西" })
User.create(name: "ch00173", password: "pwd60y46", is_admin: false, role: ["执委"], company_name: "执委：许德峰", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鸡西" })
User.create(name: "ch00174", password: "pwd51u61", is_admin: false, role: ["执委"], company_name: "执委：王月花", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "双鸭山" })
User.create(name: "ch00175", password: "pwd679j6", is_admin: false, role: ["执委"], company_name: "执委：揣永光", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "双鸭山" })
User.create(name: "ch00176", password: "pwd485k0", is_admin: false, role: ["执委"], company_name: "执委：李福源", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "双鸭山" })
User.create(name: "ch00177", password: "pwd385h8", is_admin: false, role: ["执委"], company_name: "执委：赵万里", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "双鸭山" })
User.create(name: "ch00178", password: "pwd144t5", is_admin: false, role: ["执委"], company_name: "执委：魏国栋", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "双鸭山" })
User.create(name: "ch00179", password: "pwd4370e", is_admin: false, role: ["执委"], company_name: "执委：侯要强", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "双鸭山" })
User.create(name: "ch00180", password: "pwdt3322", is_admin: false, role: ["执委"], company_name: "执委：姚松林", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "双鸭山" })
User.create(name: "ch00181", password: "pwd6h037", is_admin: false, role: ["执委"], company_name: "执委：张月辉", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "双鸭山" })
User.create(name: "ch00182", password: "pwd27j13", is_admin: false, role: ["执委"], company_name: "执委：薛  冰", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "双鸭山" })
User.create(name: "ch00183", password: "pwd641n5", is_admin: false, role: ["执委"], company_name: "执委：王晶威", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "双鸭山" })
User.create(name: "ch00184", password: "pwde6126", is_admin: false, role: ["执委"], company_name: "执委：王陆民", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "双鸭山" })
User.create(name: "ch00185", password: "pwd1r047", is_admin: false, role: ["执委"], company_name: "执委：吴学敏", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "双鸭山" })
User.create(name: "ch00186", password: "pwd65t57", is_admin: false, role: ["执委"], company_name: "执委：刘  静", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "伊春" })
User.create(name: "ch00187", password: "pwd918y8", is_admin: false, role: ["执委"], company_name: "执委：赵冬波", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "伊春" })
User.create(name: "ch00188", password: "pwd3402u", is_admin: false, role: ["执委"], company_name: "执委：赵德友", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "伊春" })
User.create(name: "ch00189", password: "pwdt1568", is_admin: false, role: ["执委"], company_name: "执委：王晓辉", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "伊春" })
User.create(name: "ch00190", password: "pwd2g159", is_admin: false, role: ["执委"], company_name: "执委：任  静", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "伊春" })
User.create(name: "ch00191", password: "pwd73b00", is_admin: false, role: ["执委"], company_name: "执委：杜帛霖", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "伊春" })
User.create(name: "ch00192", password: "pwd469n4", is_admin: false, role: ["执委"], company_name: "执委：朱  慧", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "伊春" })
User.create(name: "ch00193", password: "pwd15g45", is_admin: false, role: ["执委"], company_name: "执委：姜培恒", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "伊春" })
User.create(name: "ch00194", password: "pwd50t73", is_admin: false, role: ["执委"], company_name: "执委：王德斌", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "伊春" })
User.create(name: "ch00195", password: "pwd9y953", is_admin: false, role: ["执委"], company_name: "执委：赵松柏", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "伊春" })
User.create(name: "ch00196", password: "pwd17u02", is_admin: false, role: ["执委"], company_name: "执委：王炳烨", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "伊春" })
User.create(name: "ch00197", password: "pwd23u02", is_admin: false, role: ["执委"], company_name: "执委：石永华", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "七台河" })
User.create(name: "ch00198", password: "pwd63u36", is_admin: false, role: ["执委"], company_name: "执委：闫长彬", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "七台河" })
User.create(name: "ch00199", password: "pwd2k556", is_admin: false, role: ["执委"], company_name: "执委：焦  云", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "七台河" })
User.create(name: "ch00200", password: "pwd9g269", is_admin: false, role: ["执委"], company_name: "执委：张吉伟", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "七台河" })
User.create(name: "ch00201", password: "pwd22g37", is_admin: false, role: ["执委"], company_name: "执委：孙福文", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "七台河" })
User.create(name: "ch00202", password: "pwd23g06", is_admin: false, role: ["执委"], company_name: "执委：钟银海", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "七台河" })
User.create(name: "ch00203", password: "pwd41r55", is_admin: false, role: ["执委"], company_name: "执委：陈建君", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "七台河" })
User.create(name: "ch00204", password: "pwd93h31", is_admin: false, role: ["执委"], company_name: "执委：彭清华", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "七台河" })
User.create(name: "ch00205", password: "pwd18h88", is_admin: false, role: ["执委"], company_name: "执委：唐卫东", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "七台河" })
User.create(name: "ch00206", password: "pwd586k2", is_admin: false, role: ["执委"], company_name: "执委：李金泽", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "七台河" })
User.create(name: "ch00207", password: "pwd804h0", is_admin: false, role: ["执委"], company_name: "执委：王书玲", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鹤岗" })
User.create(name: "ch00208", password: "pwd930k2", is_admin: false, role: ["执委"], company_name: "执委：刘兆麟", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鹤岗" })
User.create(name: "ch00209", password: "pwd77m02", is_admin: false, role: ["执委"], company_name: "执委：佟振茂", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鹤岗" })
User.create(name: "ch00210", password: "pwd75k33", is_admin: false, role: ["执委"], company_name: "执委：孟繁中", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鹤岗" })
User.create(name: "ch00211", password: "pwdh1130", is_admin: false, role: ["执委"], company_name: "执委：姜  鹏", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鹤岗" })
User.create(name: "ch00212", password: "pwdu6249", is_admin: false, role: ["执委"], company_name: "执委：房泽刚", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鹤岗" })
User.create(name: "ch00213", password: "qpwd1865", is_admin: false, role: ["执委"], company_name: "执委：沙臣厚", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鹤岗" })
User.create(name: "ch00214", password: "pawd6925", is_admin: false, role: ["执委"], company_name: "执委：陈  瑞", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鹤岗" })
User.create(name: "ch00215", password: "pwsd7937", is_admin: false, role: ["执委"], company_name: "执委：侯凤祥", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鹤岗" })
User.create(name: "ch00216", password: "pwdd9269", is_admin: false, role: ["执委"], company_name: "执委：董晓宇", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鹤岗" })
User.create(name: "ch00217", password: "pwd6f301", is_admin: false, role: ["执委"], company_name: "执委：吴艳红", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鹤岗" })
User.create(name: "ch00218", password: "pwd61g45", is_admin: false, role: ["执委"], company_name: "执委：朱智勇", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "黑河" })
User.create(name: "ch00219", password: "pwd846h6", is_admin: false, role: ["执委"], company_name: "执委：张秀杰", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "黑河" })
User.create(name: "ch00220", password: "opwd9563", is_admin: false, role: ["执委"], company_name: "执委：付东坡", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "黑河" })
User.create(name: "ch00221", password: "plwd3053", is_admin: false, role: ["执委"], company_name: "执委：曹新红", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "黑河" })
User.create(name: "ch00222", password: "pwd97s34", is_admin: false, role: ["执委"], company_name: "执委：吕  炜", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "黑河" })
User.create(name: "ch00223", password: "pwmd6056", is_admin: false, role: ["执委"], company_name: "执委：孙春田", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "黑河" })
User.create(name: "ch00224", password: "pwdy6140", is_admin: false, role: ["执委"], company_name: "执委：佟宏军", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "黑河" })
User.create(name: "ch00225", password: "pwrd4143", is_admin: false, role: ["执委"], company_name: "执委：宋晓涛", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "黑河" })
User.create(name: "ch00226", password: "pwdd9741", is_admin: false, role: ["执委"], company_name: "执委：叶春泽", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "黑河" })
User.create(name: "ch00227", password: "pwd9g519", is_admin: false, role: ["执委"], company_name: "执委：陶  然", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "黑河" })
User.create(name: "ch00228", password: "pwd28h98", is_admin: false, role: ["执委"], company_name: "执委：朱宏伟", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "黑河" })
User.create(name: "ch00229", password: "pwd697u6", is_admin: false, role: ["执委"], company_name: "执委：金复杰", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "绥化" })
User.create(name: "ch00230", password: "pwd59u31", is_admin: false, role: ["执委"], company_name: "执委：张立平", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "绥化" })
User.create(name: "ch00231", password: "pwd55u30", is_admin: false, role: ["执委"], company_name: "执委：冯少臣", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "绥化" })
User.create(name: "ch00232", password: "pwd316i3", is_admin: false, role: ["执委"], company_name: "执委：张释元", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "绥化" })
User.create(name: "ch00233", password: "pwd580i1", is_admin: false, role: ["执委"], company_name: "执委：白玉明", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "绥化" })
User.create(name: "ch00234", password: "pwd1o167", is_admin: false, role: ["执委"], company_name: "执委：乔文臣", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "绥化" })
User.create(name: "ch00235", password: "pwd48u06", is_admin: false, role: ["执委"], company_name: "执委：陈彥林", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "绥化" })
User.create(name: "ch00236", password: "pwd31i13", is_admin: false, role: ["执委"], company_name: "执委：李忠珠", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "绥化" })
User.create(name: "ch00237", password: "pwd82o36", is_admin: false, role: ["执委"], company_name: "执委：赵文龙", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "绥化" })
User.create(name: "ch00238", password: "pwd54o24", is_admin: false, role: ["执委"], company_name: "执委：赵宝林", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "绥化" })
User.create(name: "ch00239", password: "pwd14o40", is_admin: false, role: ["执委"], company_name: "执委：杨晓萍", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "绥化" })
User.create(name: "ch00240", password: "pwd82o85", is_admin: false, role: ["执委"], company_name: "执委：寇立国", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "绥化" })
User.create(name: "ch00241", password: "pwd68o93", is_admin: false, role: ["执委"], company_name: "执委：曹中军", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "绥化" })
User.create(name: "ch00242", password: "pwd6d844", is_admin: false, role: ["执委"], company_name: "执委：刘晓明", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "绥化" })
User.create(name: "ch00243", password: "pwdr8981", is_admin: false, role: ["执委"], company_name: "执委：韩义文", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "绥化" })
User.create(name: "ch00244", password: "pwdf8059", is_admin: false, role: ["执委"], company_name: "执委：郭春宣", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大兴安岭" })
User.create(name: "ch00245", password: "pwd1y735", is_admin: false, role: ["执委"], company_name: "执委：周  明", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大兴安岭" })
User.create(name: "ch00246", password: "pwdt6018", is_admin: false, role: ["执委"], company_name: "执委：公明淑", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大兴安岭" })
User.create(name: "ch00247", password: "pwd1w796", is_admin: false, role: ["执委"], company_name: "执委：白沐阳", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大兴安岭" })
User.create(name: "ch00248", password: "pwd86r47", is_admin: false, role: ["执委"], company_name: "执委：张永富", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大兴安岭" })
User.create(name: "ch00249", password: "pwd21h51", is_admin: false, role: ["执委"], company_name: "执委：康金生", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大兴安岭" })
User.create(name: "ch00250", password: "pwd564m3", is_admin: false, role: ["执委"], company_name: "执委：陈燕福", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大兴安岭" })
User.create(name: "ch00251", password: "pwd25u53", is_admin: false, role: ["执委"], company_name: "执委：孙景波", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大兴安岭" })
User.create(name: "ch00252", password: "pwd16i84", is_admin: false, role: ["执委"], company_name: "执委：袁亚娟", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大兴安岭" })
User.create(name: "ch00253", password: "pwd18o61", is_admin: false, role: ["执委"], company_name: "执委：朱文革", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大兴安岭" })
User.create(name: "ch00254", password: "pwd44l26", is_admin: false, role: ["执委"], company_name: "执委：姚德坤", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大兴安岭" })
User.create(name: "ch00254", password: "pwdae426", is_admin: false, role: ["执委"], company_name: "执委：姚德坤", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大兴安岭" })

User.create(name: "coc0001", password: "pwd6q683", is_admin: false, role: ["商会"], company_name: "黑龙江省福建商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "coc0002", password: "pwd53w91", is_admin: false, role: ["商会"], company_name: "黑龙江省江西商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "coc0003", password: "pwd833e3", is_admin: false, role: ["商会"], company_name: "黑龙江省湖北商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "coc0004", password: "pwd1r220", is_admin: false, role: ["商会"], company_name: "黑龙江省物流与供应链商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "coc0005", password: "pwd81t15", is_admin: false, role: ["商会"], company_name: "黑龙江省山西商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "coc0006", password: "pwd667y7", is_admin: false, role: ["商会"], company_name: "黑龙江省江苏商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "coc0007", password: "pwd1664u", is_admin: false, role: ["商会"], company_name: "黑龙江省河北商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "coc0008", password: "pwd62i09", is_admin: false, role: ["商会"], company_name: "黑龙江省辽宁商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "coc0009", password: "pwd870d0", is_admin: false, role: ["商会"], company_name: "黑龙江省工商联房地产商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "coc0010", password: "pwd728v2", is_admin: false, role: ["商会"], company_name: "黑龙江省食品贸易商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "coc0011", password: "pwd745x0", is_admin: false, role: ["商会"], company_name: "黑龙江省泉州商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "coc0012", password: "pwd312s1", is_admin: false, role: ["商会"], company_name: "黑龙江省青年民营企业家商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "coc0013", password: "pwdg5836", is_admin: false, role: ["商会"], company_name: "黑龙江省工商联餐饮商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "��尔滨" })
User.create(name: "coc0014", password: "pwd8n197", is_admin: false, role: ["商会"], company_name: "黑龙江省古玩商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "coc0015", password: "pwd59m14", is_admin: false, role: ["商会"], company_name: "黑龙江省工商联商用家具商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "coc0016", password: "pwd171u4", is_admin: false, role: ["商会"], company_name: "黑龙江省工产业商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "coc0017", password: "pwd13k60", is_admin: false, role: ["商会"], company_name: "黑龙江省工商联科技装备商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "coc0018", password: "pwd26l18", is_admin: false, role: ["商会"], company_name: "黑龙江省潮汕商会", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })

User.create(name: "leader001", password: "pwd1f6648", is_admin: false, role: ["省工商联"], company_name: "省工商联-会员处", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "leader002", password: "pwd62d098", is_admin: false, role: ["省工商联"], company_name: "省工商联-宣教处", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "leader003", password: "pwd870g08", is_admin: false, role: ["省工商联"], company_name: "省工商联-联络处", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "leader004", password: "pwd83b338", is_admin: false, role: ["省工商联"], company_name: "省工商联-经济处", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "leader005", password: "pwd12f208", is_admin: false, role: ["省工商联"], company_name: "省工商联-机关党委", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "leader006", password: "pwd81g158", is_admin: false, role: ["省工商联"], company_name: "省工商联-法律维权处", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "leader007", password: "pwd667h78", is_admin: false, role: ["省工商联"], company_name: "省工商联-办公室", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })

User.create(name: "city0001", password: "pwdt1664", is_admin: false, role: ["市地工商联"], company_name: "市地级工商联-哈尔滨", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "哈尔滨" })
User.create(name: "city0002", password: "pwd62y09", is_admin: false, role: ["市地工商联"], company_name: "市地级工商联-齐齐哈尔", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "齐齐哈尔" })
User.create(name: "city0003", password: "pwd8u700", is_admin: false, role: ["市地工商联"], company_name: "市地级工商联-牡丹江", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "牡丹江" })
User.create(name: "city0004", password: "pwd8o333", is_admin: false, role: ["市地工商联"], company_name: "市地级工商联-佳木斯", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "佳木斯" })
User.create(name: "city0005", password: "pwd1i220", is_admin: false, role: ["市地工商联"], company_name: "市地级工商联-大庆", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大庆" })
User.create(name: "city0006", password: "pwd8o115", is_admin: false, role: ["市地工商联"], company_name: "市地级工商联-鸡西", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鸡西" })
User.create(name: "city0007", password: "pwd6n677", is_admin: false, role: ["市地工商联"], company_name: "市地级工商联-双鸭山", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "双鸭山" })
User.create(name: "city0008", password: "pwd62m17", is_admin: false, role: ["市地工商联"], company_name: "市地级工商联-伊春", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "伊春" })
User.create(name: "city0009", password: "pwd51o12", is_admin: false, role: ["市地工商联"], company_name: "市地级工商联-七台河", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "七台河" })
User.create(name: "city0010", password: "pwd75l41", is_admin: false, role: ["市地工商联"], company_name: "市地级工商联-鹤岗", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "鹤岗" })
User.create(name: "city0011", password: "pwd15l55", is_admin: false, role: ["市地工商联"], company_name: "市地级 工商联-黑河", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "黑河" })
User.create(name: "city0012", password: "pwd7l141", is_admin: false, role: ["市地工商联"], company_name: "市地级工商联-绥化", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "绥化" })
User.create(name: "city0013", password: "pwd754l2", is_admin: false, role: ["市地工商联"], company_name: "市地级工商联-大兴安岭", user_uuid: Digest::UUID.uuid_v4.to_s, address: { province: "黑龙江", city: "大兴安岭" })

